### ISSUE TITLE
This is for lbaas v1, v2 is different

### ISSUE THREAD

**Issue by kramvan1** [svashu/devstack-lbaas#1]
Might want to make that clear in your readme.
See https://github.com/openstack/neutron-lbaas/tree/master/devstack for more details on lbaas v2. Note that the default provider is Octivia which spins up a nested vm (amphora) which can be very slow on qemu systems.

**Comment by coolsvap** [comment]
Thanks @kramvan1 I will see the v2 details and will post for v2 as well
